// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Oracle.EntityFrameworkCore.Metadata;
using Vision.Hive.Infrastructure.Contexts;

#nullable disable

namespace Vision.Hive.Migrations
{
    [DbContext(typeof(VisionHiveContext))]
    [Migration("20250516194714_InitialTesteCreate")]
    partial class InitialTesteCreate
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.13")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            OracleModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("Vision.Hive.Infrastructure.Persistence.Area", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("RAW(16)");

                    b.Property<string>("Nome")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("NVARCHAR2(100)");

                    b.HasKey("Id");

                    b.ToTable("Areas", (string)null);
                });

            modelBuilder.Entity("Vision.Hive.Infrastructure.Persistence.Moto", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("RAW(16)");

                    b.Property<Guid>("AreaId")
                        .HasColumnType("RAW(16)");

                    b.Property<Guid?>("AreaId1")
                        .HasColumnType("RAW(16)");

                    b.Property<string>("Chassi")
                        .HasMaxLength(30)
                        .HasColumnType("NVARCHAR2(30)");

                    b.Property<DateTime>("DateCreated")
                        .HasColumnType("TIMESTAMP(7)");

                    b.Property<DateTime>("DateModified")
                        .HasColumnType("TIMESTAMP(7)");

                    b.Property<string>("NumeroMotor")
                        .HasMaxLength(30)
                        .HasColumnType("NVARCHAR2(30)");

                    b.Property<string>("Placa")
                        .HasMaxLength(10)
                        .HasColumnType("NVARCHAR2(10)");

                    b.Property<int>("Prioridade")
                        .HasColumnType("NUMBER(10)");

                    b.HasKey("Id");

                    b.HasIndex("AreaId");

                    b.HasIndex("AreaId1");

                    b.ToTable("Motos", (string)null);
                });

            modelBuilder.Entity("Vision.Hive.Infrastructure.Persistence.Moto", b =>
                {
                    b.HasOne("Vision.Hive.Infrastructure.Persistence.Area", "Area")
                        .WithMany()
                        .HasForeignKey("AreaId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Vision.Hive.Infrastructure.Persistence.Area", null)
                        .WithMany("Motos")
                        .HasForeignKey("AreaId1");

                    b.Navigation("Area");
                });

            modelBuilder.Entity("Vision.Hive.Infrastructure.Persistence.Area", b =>
                {
                    b.Navigation("Motos");
                });
#pragma warning restore 612, 618
        }
    }
}
