// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Oracle.EntityFrameworkCore.Metadata;
using Vision.Hive.Infrastructure.Contexts;

#nullable disable

namespace Vision.Hive.Migrations
{
    [DbContext(typeof(VisionHiveContext))]
    partial class VisionHiveContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.13")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            OracleModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("Vision.Hive.Infrastructure.Persistence.Filial", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("RAW(16)");

                    b.Property<string>("Bairro")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("NVARCHAR2(100)");

                    b.Property<string>("Cnpj")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("NVARCHAR2(20)");

                    b.Property<string>("Nome")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("NVARCHAR2(100)");

                    b.HasKey("Id");

                    b.ToTable("Filiais", (string)null);
                });

            modelBuilder.Entity("Vision.Hive.Infrastructure.Persistence.Moto", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("RAW(16)");

                    b.Property<string>("Chassi")
                        .HasMaxLength(30)
                        .HasColumnType("NVARCHAR2(30)");

                    b.Property<DateTime>("DateCreated")
                        .HasColumnType("TIMESTAMP(7)");

                    b.Property<DateTime>("DateModified")
                        .HasColumnType("TIMESTAMP(7)");

                    b.Property<string>("NumeroMotor")
                        .HasMaxLength(30)
                        .HasColumnType("NVARCHAR2(30)");

                    b.Property<Guid>("PatioId")
                        .HasColumnType("RAW(16)");

                    b.Property<string>("Placa")
                        .HasMaxLength(10)
                        .HasColumnType("NVARCHAR2(10)");

                    b.Property<int>("Prioridade")
                        .HasColumnType("NUMBER(10)");

                    b.HasKey("Id");

                    b.HasIndex("PatioId");

                    b.ToTable("Motos", (string)null);
                });

            modelBuilder.Entity("Vision.Hive.Infrastructure.Persistence.Patio", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("RAW(16)");

                    b.Property<Guid>("FilialId")
                        .HasColumnType("RAW(16)");

                    b.Property<int>("LimiteMotos")
                        .HasColumnType("NUMBER(10)");

                    b.Property<string>("Nome")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("NVARCHAR2(100)");

                    b.HasKey("Id");

                    b.HasIndex("FilialId");

                    b.ToTable("Patios", (string)null);
                });

            modelBuilder.Entity("Vision.Hive.Infrastructure.Persistence.Moto", b =>
                {
                    b.HasOne("Vision.Hive.Infrastructure.Persistence.Patio", "Patio")
                        .WithMany("Motos")
                        .HasForeignKey("PatioId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Patio");
                });

            modelBuilder.Entity("Vision.Hive.Infrastructure.Persistence.Patio", b =>
                {
                    b.HasOne("Vision.Hive.Infrastructure.Persistence.Filial", "Filial")
                        .WithMany("Patios")
                        .HasForeignKey("FilialId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Filial");
                });

            modelBuilder.Entity("Vision.Hive.Infrastructure.Persistence.Filial", b =>
                {
                    b.Navigation("Patios");
                });

            modelBuilder.Entity("Vision.Hive.Infrastructure.Persistence.Patio", b =>
                {
                    b.Navigation("Motos");
                });
#pragma warning restore 612, 618
        }
    }
}
